---
name: Fork Sync with Upstream
on:
  schedule:
    - cron: '0 20 * * 0'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.0
        with:
          upstream_repository: panr/hugo-theme-hello-friend
          upstream_branch: master
          target_branch: master
          git_pull_args: --ff-only
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits
        run: echo "There were new commits."

      - name: Timestamp
        run: date
